# Generated by Django 4.2.1 on 2023-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_pdates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdates',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
